# Generated by Django 3.2.9 on 2021-11-06 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 11, 6, 16, 7, 56, 495081, tzinfo=utc)),
        ),
    ]
