# Generated by Django 3.2.9 on 2021-11-06 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_article_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='caterogy',
            new_name='category',
        ),
    ]
