# Generated by Django 3.2.9 on 2021-11-06 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_pub_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_time',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
