# Generated by Django 3.2.9 on 2021-11-03 15:32

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_release_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="country",
            field=django_countries.fields.CountryField(default="FR", max_length=2),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(default="John Doe", max_length=200),
            preserve_default=False,
        ),
    ]
