# Generated by Django 3.2.9 on 2021-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20211103_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='showing',
            name='language',
            field=models.CharField(choices=[('VO', 'VOST'), ('VF', 'VF')], default='VF', max_length=2),
        ),
    ]
